<?php

namespace app\modules\su\controllers;

use app\models\ExcelForm;
use app\models\Msg;
use app\models\Student;
use app\models\Su;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\UploadedFile;

class IndexController extends Controller
{
    public $layout = 'sulayout';

    public function beforeAction($action)
    {
        /**
         *  通过session进行登录验证
         *  如果action的getUniqueId是'su/index/login'
         *  防止循环重定向,进行一个判断
         */
        if ($action->getUniqueId() !== 'su/index/login') {
            $session = \Yii::$app->session;
            $session->open();
            if ($session['yii']['type'] != 'su' || $session['yii']['islogin'] != 1) {
                return $this->redirect(Url::toRoute('index/login'));
            } else {
                return parent::beforeAction($action);
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        $this->layout = 'main';
        if (\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
            $model = Su::findOne($post['Su']);
            if (empty($model)) {
                $model = new Su();
                $model->username = $post['Su']['username'];
                return $this->render('login', ['model' => $model]);
            }
            $session = \Yii::$app->session;
            $session->remove('yii');
            $session['yii'] = [
                'type' => 'su',
                'islogin' => 1,
                'name' => 'su'
            ];
            return $this->redirect(Url::toRoute('index/index'));
        } else {
            $model = new Su();
            return $this->render('login', ['model' => $model]);
        }

    }

    public function actionTeachercurd()
    {
        return $this->redirect(Url::toRoute('teachercurd/index'));
    }

    /**
     * @return string
     * 上传excel文件,读取excel导入数据库
     */
    public function actionImportstudent()
    {
        //TODO
        //$exceldir = \Yii::getAlias('@app') . "/excel/";
//        $filename = $exceldir . 'excel1.xls';

        $model = new ExcelForm();
        if (\Yii::$app->request->isPost) {
            $model->excel = UploadedFile::getInstance($model, 'excel');
            if (($excelname = $model->upload()) != false) {
                $excelobj = \PHPExcel_IOFactory::load($excelname);
                $data = $excelobj->getSheet(0)->toArray();
                $post = \Yii::$app->request->post();
                if ($post['ExcelForm']['delete'] == true) {
                    Student::deleteAll();
                }
//                var_dump($data);
//数据可以获得  当时无法插入数据
                $db = \Yii::$app->db;
                foreach ($data as $item) {
                   echo $db->createCommand('INSERT INTO `student`( `num`, `pwd`, `name`) VALUES (:num,:pwd,:name)', [
                        ':name' => $item[1],
                        ':num' => $item[0],
                        ':pwd' => $item[0],
                    ])->execute();
                }
            } else {
                echo 'uploadFail';
            }
        }

        return $this->render('importstudent', ['model' => $model]);
    }

    public function actionEditmsg()
    {
        $model = (Msg::findOne(['id' => 1] != null) ? Msg::findOne(['id' => '1']) : (new Msg()));
        if (\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
            $model->content = $post['Msg']['content'];
            $model->html = $post['Msg']['html'];
            $model->save();
        }
        return $this->render('editmsg', ['model' => $model]);
    }


    public function actionDeletedata()
    {
        if (\Yii::$app->request->isAjax) {
            echo Student::deleteAll();
            exit();
        }
        return $this->render('deletedata');
    }


}
