<?php

namespace app\modules\su\controllers;

use app\models\ExcelForm;
use app\models\Msg;
use app\models\Su;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\UploadedFile;

class IndexController extends Controller
{
    public $layout = 'sulayout';

    public function beforeAction($action)
    {
        /**
         *  通过session进行登录验证
         *  如果action的getUniqueId是'su/index/login'
         *  防止循环重定向,进行一个判断
         */
        if ($action->getUniqueId() !== 'su/index/login') {
            $session = \Yii::$app->session;
            $session->open();
            if ($session['yii']['type'] != 'su' || $session['yii']['islogin'] != 1) {
                return $this->redirect(Url::toRoute('index/login'));
            } else {
                return parent::beforeAction($action);
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        $this->layout = 'main';
        if (\Yii::$app->request->isPost) {
            $model = Su::findOne($_POST['Su']);
            if (empty($model)) {
                $model = new Su();
                return $this->render('login', ['model' => $model]);
            }
            $session = \Yii::$app->session;
            $session->destroy();
            $session['yii'] = [
                'type' => 'su',
                'islogin' => 1,
                'name' => 'su'
            ];
            return $this->redirect(Url::toRoute('index/index'));
        } else {
            $model = new Su();
            return $this->render('login', ['model' => $model]);
        }

    }

    public function actionTeachercurd()
    {
        return $this->redirect(Url::toRoute('teachercurd/index'));
    }

    /**
     * @return string
     * 上传excel文件,读取excel导入数据库
     */
    public function actionImportstudent()
    {
        //TODO
        $exceldir = \Yii::getAlias('@app') . "/excel/";
//        $filename = $exceldir . 'excel1.xls';
//        $excelobj = \PHPExcel_IOFactory::load($filename);
//        $sheetcount =  $excelobj->getSheetCount();
//        $data = $excelobj->getSheet(2)->toArray();
        $model = new ExcelForm();
        if (\Yii::$app->request->isPost) {
            $model->excel = UploadedFile::getInstance($model, 'excel');
            if ($model->validate()) {
//                $model->file->saveAs('uploads/' . $model->file->baseName . '.' . $model->file->extension);
                echo $model->excel->baseName . '.' . $model->excel->extension;
                exit();
            }
        }

        return $this->render('importstudent', ['model' => $model]);
    }

    public function actionEditmsg()
    {
        $model = (Msg::findOne(['id' => 1] != null) ? Msg::findOne(['id' => '1']) : (new Msg()));
        if (\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
            $model->content = $post['Msg']['content'];
            $model->html = $post['Msg']['html'];
            $model->save();
        }
        return $this->render('editmsg', ['model' => $model]);
    }
}
