<?php

namespace app\controllers;

use app\models\Student;
use yii\helpers\Url;
use yii;

class IndexController extends \yii\web\Controller
{
    public $layout = 'main';

    public function actionIndex()
    {
        $session = yii::$app->session;
        $session->open();
        return $this->render('index');
    }

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionLogin()
    {
        $model = new Student();
        $postarr = yii::$app->request->post();
        //如果post数组为空这直接显示login界面
        if (empty($postarr['Student'])) {
            return $this->render('login', ['model' => $model, 'msg' => '']);
        } else {
            if ($res = $model->findOne($postarr['Student'])) {
                $session = yii::$app->session;
                $session->open();
                $session->destroy();
                $session['yii'] = [
                    'type' => 'xs',
                    'name' => $res['name'],
                    'num' => $res['num'],
                    'id'=>$res['id'],
                    'islogin' => 1
                ];
                return $this->redirect(Url::toRoute(['/student/index']));
            } else {
                //fail
                return $this->render('login', ['model' => $model, 'msg' => '学号或密码错误']);
            }
        }
    }



    public function actionLogout()
    {
        $session  = Yii::$app->session;
        $session->open();
        $session->destroy();
        return $this->render('index');
    }
}
