<?php

namespace app\modules\teacher\controllers;

use app\models\Teacher;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use Yii;

class IndexController extends Controller
{
    public $layout = "teacherlayout";
    public function beforeAction($action)
    {
        /**
         *  通过session进行登录验证
         *  如果action的getUniqueId是'su/index/login'
         *  防止循环重定向,进行一个判断
         */
        if ($action->getUniqueId() !== 'teacher/index/login') {
            $session = \Yii::$app->session;
            $session->open();
            if ($session['yii']['type'] != 't' || $session['yii']['islogin'] != 1) {
                return $this->redirect(Url::toRoute('index/login'));
            } else {
                return parent::beforeAction($action);
            }
        }


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }


    public function actionLogin()
    {
        $this->layout='main';
        if (\Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            $model = Teacher::findOne($post['Teacher']);
            if (empty($model)) {
                $model = new Teacher();
                $model->num=$post['Teacher']['num'];
                return $this->render('login', ['model' => $model]);
            }
            $session = \Yii::$app->session;
            $session->open();
            $session->remove('yii');
            $session['yii'] = [
                'type' => 't',
                'islogin' => 1,
                'id'=>$model->id,
                'num'=>$model->num,
                'name' => $model->name
            ];
            return $this->redirect(Url::toRoute('index/index'));
        } else {
            $model = new Teacher();
            return $this->render('login', ['model' => $model]);
        }
    }

    /**
     *老师信息编辑
     */
    public function actionEdit()
    {

    }

    /**
     * 老师学生关系
     */
    public function actionRelative()
    {
    }

    /**
     * 检查学生的毕业设计选题是否合格
     */
    public function actionSubjectok()
    {

    }
}
